name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # ✅ 移除 "Setup Gradle" 步驟，避免觸發快取錯誤

    - name: Grant execute permission
      run: chmod +x ./gradlew

    - name: Build debug APK
      run: ./gradlew --no-daemon --no-parallel assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug-apk
